import "./globals.css";
import type { Metadata } from "next";
import { vazirFont } from "@/utils/fonts";
import React from "react";
import Layout from "../components/layout/Layout";

type Trootlayout = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Trootlayout) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className}>
        <Layout>{children}</Layout>
        
      </body>
    </html>
  );
}
