import './globals.css'
import type { Metadata } from 'next'
import { vazirFont } from '@/utils/fonts'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body className={vazirFont.className}>{children}</body>
    </html>
  )
}
